# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "my_first_branch" ]
  pull_request:
    branches: [ "my_first_branch" ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:
jobs:
  print_sayhello:
    runs-on: ubuntu:latest
    steps:
      - name: sayHello
        run: echo "sayhello"
